### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by dabao40** [EnoPM/BetterOtherRoles#1]
**Describe the bug**
Undertaker can still kill other players even if the former is dragging a body

**To Reproduce**
1. I'm using local Among Us to test out Undertaker and see how it works for BetterOtherRoles and to test it out also for my mod, which is licensed under GPL-3.0
2. Kill anyone who is not the Jackal and drag the dead body
3. See error

**Expected behavior**
The Kill button should not work and if the Undertaker tries to click the button nothing should happen.

**Screenshots**
![image](https://github.com/EnoPM/BetterOtherRoles/assets/73883362/3a93b388-e99e-441e-8ac4-1f512e6607f6)

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version v2023.7.12s
 - Better Other Roles Version: Latest

**Comment by dabao40** [comment]
It is recommended to add the set target thingy in the ImpostorSetTarget function which is situated in PlayerControlPatch.cs instead of adding some random lines in UpdatePatch.cs that may cause the Undertaker to break.  
Using the Palette.DisabledClear may cause the some severe problems. Please Delete the line and add the following line in PlayerControlPatch.cs if you have seen this review.  
![image](https://github.com/EnoPM/BetterOtherRoles/assets/73883362/d0ccfdce-5633-45a5-81ef-c44fc4364d40)
This is located in the function called "impostorSetTarget"

**Comment by EnoPM** [comment]
I've changed that. Thanks you.
